### ISSUE TITLE
Empty GHPython component breaks the parser!!!!!!!!!

### ISSUE THREAD

**Issue by kangoananya** [LinCheWei/Membracidae#1]
Hello!

I tried it on my file and it breaks if there is an empty GHpython component in the canvas. HELPPP!!

![image](https://github.com/LinCheWei/Membracidae/assets/91247934/a074dbba-de50-4fd0-88a8-adffe3dc2a2d)

**Comment by LinCheWei** [comment]
Okay, I’ll check it out. You said it won’t work if there’s a empty Python
component?

**Comment by LinCheWei** [comment]
Problem solve, I pushed a fixed version just now. I'll figure out a way to get rid of this silly dictionary system soon.
